### ISSUE TITLE
Comparison of finite and automatic differentiation procedures.

### ISSUE THREAD

**Issue by andrevitorelli** [CosmoStat/autometacal#18]
This is an investigation of the difference between doing _automatic differentiation_ and _finite differences_ for computing the response matrix. We will have plots like this below, from  [Yahia-Cherif et al 2021](https://ui.adsabs.harvard.edu/abs/2021A%26A...649A..52Y/abstract).

<img src="https://user-images.githubusercontent.com/7417573/123252858-07e94d80-d4ed-11eb-9043-6e73207db5b2.png" width="320" height="240">

...where in x we will look at different finite step sizes, and y the resulting relative difference between methods.

**Comment by andrevitorelli** [comment]
Comparing finite vs automatic differentiation for simple 2 points in each direction (1p,1m,2p,2m) - and on a single image -  we get this:
![autofinite](https://user-images.githubusercontent.com/7417573/123708866-6c4d3980-d86c-11eb-9033-d3f9afc22e9f.jpeg)

**Comment by andrevitorelli** [comment]
The notebook is here: https://github.com/CosmoStat/autometacal/blob/mcal_auto_finite_test/notebooks/metacal_compare_auto_finite.ipynb 
More to come.

**Comment by andrevitorelli** [comment]
Comparing finite vs automatic differentiation for simple 2 points in each direction (1p,1m,2p,2m) - and on a single image - we get this:
![autofinite1624917908 1275868](https://user-images.githubusercontent.com/7417573/123709717-d2868c00-d86d-11eb-9916-9ffedd9a62c9.jpeg)

**Comment by andrevitorelli** [comment]
Nb is here: https://github.com/CosmoStat/autometacal/blob/e5a43752ebc5ca05d4c1d2e8aa2db6d5de5a00a9/notebooks/metacal_compare_auto_finite.ipynb

**Comment by EiffL** [comment]
Fantastic, very nice! Yes this is what we want :-) 
But I was thinking about a plot of the R matrix than ellipticity. This plot is still very interesting, and if I understand correctly, you apply the inverse R matrix obtained with either form of metacal and you compare the "calibrated" ellipticities. So it's nice because it tells us how an error on the response matrix might translate into a calibration error.

So, two things:
- Can you make the same plot but for the components of the response matrix itself? (like R11 R22)

- Can you add a small shear on your input galaxy object? like g1=0.01, so that we have a non-zero baseline for the ellipticity?

**Comment by andrevitorelli** [comment]
Here: 
![autofinite_response1624956019 4873207](https://user-images.githubusercontent.com/7417573/123765959-84ea3d80-d8c6-11eb-95f7-640b376279d8.jpeg)

**Comment by andrevitorelli** [comment]
Nothing changes with a slightly sheared 'galaxy' (g1=0.05):
![autofinite1624959558 9800317](https://user-images.githubusercontent.com/7417573/123775772-f6c68500-d8ce-11eb-8a1d-a13517d048ea.jpeg)
![autofinite_response_log](https://user-images.githubusercontent.com/7417573/123775793-fc23cf80-d8ce-11eb-91f0-0659403f2cac.jpeg)

**Comment by andrevitorelli** [comment]
With additional noise, off-diagonal elements rise. 
![autofinite_response_log](https://user-images.githubusercontent.com/7417573/123785087-65f4a700-d8d8-11eb-8eb7-5dced50314b8.jpeg)

**Comment by EiffL** [comment]
So that's pretty interesting! We see a non-zero bias at 1e-2 in this case with noise for the diagonal terms of the response matrix :-) 

Alright, so I would suggest the following to make plots for the paper:

- [ ] We could plot on the y-axis the relative error on R components, to have all 4 components scaled approximately in the same way.

- [ ] We could add a vertical line at the usual choice of 0.01 for the step, to guide the eye

- [ ] We could make this plot for like a few galaxies of different SNR and size, just to see if we can see an difference in behaviour in different situations, and/or if we see an apparent effect, whether it's by chance or typical (I'm thinking for instance of this plot above with noise). Then for the paper we keep only a few typical examples. 

- [ ] The next question we will need to ask is whether this effect is significant when computing the mean response over a large sample of galaxies. 

In any case, I think we can start by adding a section on this comparison in the paper @andrevitorelli :-)

**Comment by andrevitorelli** [comment]
I'm not sure on plotting relative residuals at the moment, because there are important differences in magnitudes between diagonal and off diagonal elements in different scenarios that are washed away in relative residuals. I think this is actually due to implementation problems, and after these are resolved, a final plot with relative residuals would make sense, as we're only interested in overall behaviour.

**Comment by andrevitorelli** [comment]
I am still trying to understand why the derivative differences are so stable between different images. This was created from the median, and CL68 and 95 regions of absolute differences between auto and finite differentiation over 100 galaxy images.
![median_response](https://user-images.githubusercontent.com/7417573/124580141-22f28080-de50-11eb-8771-8dff13dc2bb2.png)

**Comment by andrevitorelli** [comment]
Next tasks down the road to close this issue:

- [ ] Batching the finite differences function
- [ ] Plots with different noise levels
- [ ] Plots with different pixel scales
Bonus mission?
- [ ] Porting the ngmix/moments.py to get_ellipticities() and rerun.

**Comment by andrevitorelli** [comment]
Some results with different noise levels
![median_response_100x_noise](https://user-images.githubusercontent.com/7417573/125422031-a57dfe94-d90f-4fa7-ad5d-50f57e7f6d01.png)
![median_response_10x_noise](https://user-images.githubusercontent.com/7417573/125422034-f3437f01-79f0-4fb1-b79a-e647beefa28b.png)
![median_response](https://user-images.githubusercontent.com/7417573/125422036-7b8e9554-8ad2-4e47-bc2e-6b93a8e1153b.png)

**Comment by andrevitorelli** [comment]
- [ ] Derivatives of the images regarding to shear
- [ ] plotting shear response distribution different

**Comment by andrevitorelli** [comment]
- [ ] check different noise levels with the plateaus (with ODD pixel-sized stamp)
- [ ] plot with float64
- [ ] cpu vs gpu

**Comment by EiffL** [comment]
ok, so, what happens with float 64 and cpu vs gpu?

**Comment by andrevitorelli** [comment]
@EiffL with even number of pixels, the autodiff vs finite differences go on getting closer and up to the step size of 1e-5 - instead of rising back again (the relative differences between methods become as low as 1e-7).
With odd number of pixels nothing changes, the plateau is there.
